// src/AureliaStandards.WebApp/src/react/list.tsx
﻿import * as moment from 'moment';
import * as React from "react";

import { TasksApi } from './tasks-api';
import { TasksData } from '../shared/tasks-data';
import { ITaskItem } from '../shared/task-item';

interface IState {
    formTaskTitle: string,
    formTaskDetails: string,
    isDataLoading: boolean,
    tasksData: TasksData
}

interface IProps {
    tasksApi: TasksApi,
    tasksData: TasksData
}

export class List extends React.Component<IProps, IState> {
    private api: TasksApi;

    constructor(props) {
        super(props);

        this.state = {
            formTaskTitle: '',
            formTaskDetails: '',
            isDataLoading: false,
            tasksData: props.tasksData
        };

        this.api = this.props.tasksApi;

        this.addTask = this.addTask.bind(this);
        this.handleformTaskTitleChange = this.handleformTaskTitleChange.bind(this);
        this.handleformTaskDetailsChange = this.handleformTaskDetailsChange.bind(this);
        this.getAllTasks = this.getAllTasks.bind(this);
        this.updateTask = this.updateTask.bind(this);

        if (!this.state.tasksData.items.length) {
            this.getAllTasks();
        }
    }

    public get activeTasksCount(): number {
        return this.activeTasksItems.length;
    }

    public get activeTasksItems(): ITaskItem[] {
        return this.state.tasksData.items.filter(x => !x.isDone);
    }

    public get doneTasksCount(): number {
        return this.doneTasksItems.length;
    }

    public get doneTasksItems(): ITaskItem[] {
        return this.state.tasksData.items.filter(x => x.isDone);
    }

    public render(): JSX.Element {
        let isLoadingEl = this.state.isDataLoading ? <em className="small">(Loading...)</em> : undefined;

        let updateButtonEl = !this.state.isDataLoading
            ? <button onClick={this.getAllTasks} className="btn btn-default btn-sm">Update</button>
            : undefined;

        let activeTasksEl = this.getTasksEl(this.activeTasksItems, this.activeTasksCount, 'Active items');
        let doneTasksEl = this.getTasksEl(this.doneTasksItems, this.doneTasksCount, 'Done items', true /*isDoneItems*/);

        return <div>
            <h2>
                List {isLoadingEl} {updateButtonEl}
            </h2>
            <form onSubmit={this.addTask}>
                <div className="form-group">
                    <label htmlFor="title">Title</label>
                    <input value={this.state.formTaskTitle} onChange={this.handleformTaskTitleChange} disabled={this.state.isDataLoading}
                        type="text" id="title" placeholder="Title" className="form-control" />
                </div>
                <div className="form-group">
                    <label htmlFor="details">Details</label>
                    <textarea value={this.state.formTaskDetails} onChange={this.handleformTaskDetailsChange} disabled={this.state.isDataLoading}
                        id="details" placeholder="Details" className="form-control"></textarea>
                </div>
                <button disabled={this.state.isDataLoading || !this.state.formTaskTitle || this.state.formTaskTitle.length < 3}
                    type="submit" className="btn btn-default">Add</button>
            </form>
            {activeTasksEl}
            {doneTasksEl}
        </div>;
    }

    public addTask(event): void {
        this.setState({ isDataLoading: true });

        this.api.add(this.state.formTaskTitle, this.state.formTaskDetails)
            .then(data => {
                this.state.tasksData.items.push(data);

                this.sortItems();

                this.setState({ formTaskDetails: '', formTaskTitle: '' });
            })
            .then(() => {
                this.setState({ isDataLoading: false });
            });

        event.preventDefault();
    }

    public getAllTasks(): void {
        this.setState({ isDataLoading: true });

        this.state.tasksData.items.length = 0;
        this.state.tasksData.items.splice(0, this.state.tasksData.items.length);

        this.api.getAll()
            .then(data => {
                data.forEach(x => this.state.tasksData.items.push(x));

                this.sortItems();

                this.setState({ tasksData: this.state.tasksData });
            })
            .then(() => {
                this.setState({ isDataLoading: false });
            });
    }

    public updateTask(task: ITaskItem): void {
        this.setState({ isDataLoading: true });

        task.isDone = !task.isDone;

        this.api.update(task)
            .then(data => {
                let existingTask = this.state.tasksData.items.find(x => x.id === data.id);
                if (existingTask) {
                    let index = this.state.tasksData.items.indexOf(existingTask);

                    if (index >= 0) {
                        this.state.tasksData.items.splice(index, 1, data);
                    }
                }

                this.sortItems();
            })
            .then(() => {
                this.setState({ isDataLoading: false });
            });
    }

    public deleteTask(task: ITaskItem): void {
        let isConfirmed = confirm('Are you sure you want to delete this item?');
        if (!isConfirmed) {
            return;
        }

        this.setState({ isDataLoading: true });

        this.api.deleteItem(task.id)
            .then(() => {
                let index = this.state.tasksData.items.indexOf(task);

                if (index >= 0) {
                    this.state.tasksData.items.splice(index, 1);
                }

                this.sortItems();
            })
            .then(() => {
                this.setState({ isDataLoading: false });
            });
    }

    private getDateFormatRelative(value): string {
        return moment(value).fromNow();
    }

    private getDateFormat(value, format): string {
        return moment(value).format(format);
    }

    private getTasksEl(taskItems: ITaskItem[], tasksCount: number, titleText: string, isDoneTasks: boolean = false): JSX.Element {
        let activeTasksCountEl = tasksCount ? <span className="badge">{tasksCount}</span> : undefined;

        let tasksItemsEls = taskItems.map(task => {
            let detailsTextEl = (!isDoneTasks && task.detailsText)
                ? <p title="{task.detailsText}">
                    {task.detailsText}
                </p>
                : undefined;

            return <div className={task.isDone ? 'list-group-item list-group-item-success strike-through' : 'list-group-item'}>
                <h4>
                    <input checked={task.isDone} onChange={() => this.updateTask(task)}
                        type="checkbox" id={'checkbox-' + task.id} />&nbsp;
                        <label htmlFor={'checkbox-' + task.id}>
                        {task.titleText}
                    </label>
                    &nbsp;
                    <a className="btn btn-default btn-xs disabled">
                        Show details &gt;
                    </a>
                    &nbsp;                    
                    <button onClick={() => this.deleteTask(task)} className="btn btn-danger btn-xs">
                    Delete
                </button>
                </h4>
                {detailsTextEl}
                <div>
                    <span title={'Updated at ' + this.getDateFormat(task.updatedAt, 'YYYY-MM-DD HH:mm:ss')} className="label label-info">
                        Updated: {this.getDateFormatRelative(task.updatedAt)}
                    </span>&nbsp;&nbsp;
                    <span className="label label-default">
                        Created: {this.getDateFormat(task.createdAt, 'YYYY-MM-DD')}
                    </span>
                </div>
            </div>
        });

        let tasksEl = taskItems.length
            ? <div className="list-group">
                <h3>
                    {titleText} {activeTasksCountEl}
                </h3>

                {tasksItemsEls}
            </div>
            : undefined;
        return tasksEl;
    }

    private handleformTaskTitleChange(event): void {
        this.setState({ formTaskTitle: event.target.value });
    }

    private handleformTaskDetailsChange(event): void {
        this.setState({ formTaskDetails: event.target.value });
    }

    private sortItems(): void {
        this.state.tasksData.items.sort((a, b) => {
            let aTitle = (a.titleText || '').toLowerCase();
            let bTitle = (b.titleText || '').toLowerCase();

            if (aTitle < bTitle) {
                return -1;
            }
            if (aTitle > bTitle) {
                return 1;
            }
            return 0;
        });
    }
}

// src/AureliaStandards.WebApp/src/angular/list.component.ts
﻿import { Component } from "@angular/core";

import { TasksApiService } from './tasks-api.service';
import { TasksData } from './tasks-data';
import { ITaskItem } from '../shared/task-item';

@Component({
    selector: 'list',
    templateUrl: './dist/templates/list.component.html'
    // TestABC
})
export class ListComponent {
    private _formTaskDetails: string;
    private _formTaskTitle: string = '';
    private _tasksData: TasksData;

    constructor(tasksData: TasksData,
        private api: TasksApiService) {
        this._tasksData = tasksData;

        if (!this._tasksData.items.length) {
            this.getAllTasks();
        }
    }

    public get formTaskDetails(): string {
        return this._formTaskDetails;
    }

    public set formTaskDetails(value: string) {
        this._formTaskDetails = value;
    }

    public get formTaskTitle(): string {
        return this._formTaskTitle;
    }

    public set formTaskTitle(value: string) {
        this._formTaskTitle = value;
    }

    public get activeTasksCount(): number {
        return this.activeTasksItems.length;
    }

    public get activeTasksItems(): ITaskItem[] {
        return this._tasksData.items.filter(x => !x.isDone);
    }

    public get doneTasksCount(): number {
        return this.doneTaskItems.length;
    }

    public get doneTaskItems(): ITaskItem[] {
        return this._tasksData.items.filter(x => x.isDone);
    }

    public isDataLoading: boolean = false;

    public addTask(): void {
        this.isDataLoading = true;

        this.api.add(this.formTaskTitle, this.formTaskDetails)
            .then(data => {
                this._tasksData.items.push(data);

                this.sortItems();

                this.formTaskTitle = '';
                this.formTaskDetails = '';
            })
            .then(() => {
                this.isDataLoading = false;
            });
    }

    public deleteTask(task: ITaskItem): void {
        let isConfirmed = confirm('Are you sure you want to delete this item?');
        if (!isConfirmed) {
            return;
        }

        this.isDataLoading = true;

        this.api.deleteItem(task.id)
            .then(() => {
                let index = this._tasksData.items.indexOf(task);

                if (index >= 0) {
                    this._tasksData.items.splice(index, 1);
                }

                this.sortItems();
            })
            .then(() => {
                this.isDataLoading = false;
            });
    }

    public getAllTasks(): void {
        this.isDataLoading = true;

        this._tasksData.items.length = 0;
        this._tasksData.items.splice(0, this._tasksData.items.length);

        this.api.getAll()
            .then(data => {
                data.forEach(x => this._tasksData.items.push(x));

                this.sortItems();
            })
            .then(() => {
                this.isDataLoading = false;
            });
    }

    public updateTask(task: ITaskItem): void {
        this.isDataLoading = true;

        this.api.update(task)
            .then(data => {
                let existingTask = this._tasksData.items.find(x => x.id === data.id);
                if (existingTask) {
                    let index = this._tasksData.items.indexOf(existingTask);

                    if (index >= 0) {
                        this._tasksData.items.splice(index, 1, data);
                    }
                }

                this.sortItems();
            })
            .then(() => {
                this.isDataLoading = false;
            });
    }

    private sortItems(): void {
        this._tasksData.items.sort((a, b) => {
            let aTitle = (a.titleText || '').toLowerCase();
            let bTitle = (b.titleText || '').toLowerCase();

            if (aTitle < bTitle) {
                return -1;
            }
            if (aTitle > bTitle) {
                return 1;
            }
            return 0;
        });
    }
}
﻿<h2>
    List
    <em *ngIf="isDataLoading" class="small">(Loading...)</em>
    <button *ngIf="!isDataLoading" (click)="getAllTasks()" class="btn btn-default btn-sm">Update</button>
</h2>
    
<form>
    <div class="form-group">
        <label for="title">Title</label>
        <input [disabled]="isDataLoading" [(ngModel)]="formTaskTitle"
               type="text" id="title" name="title" placeholder="Title" class="form-control">
    </div>
    <div class="form-group">
        <label for="details">Details</label>
        <textarea [disabled]="isDataLoading" [(ngModel)]="formTaskDetails"
                        type="text" id="details" name="details" placeholder="Details" class="form-control"></textarea>
    </div>
    <button (click)="addTask()" [disabled]="isDataLoading || !formTaskTitle || formTaskTitle.length < 3"
            type="submit" class="btn btn-default">Add</button>
</form>

<div *ngIf="activeTasksItems.length" class="list-group">
    <h3>
        Active items
        <span *ngIf="activeTasksCount" class="badge">
            {{activeTasksCount}}
        </span>
    </h3>

    <div *ngFor="let task of activeTasksItems"
         class="list-group-item {{task.isDone ? 'strike-through' : ''}}">
        <h4>
            <input [(ngModel)]="task.isDone" (change)="updateTask(task)"
                   type="checkbox" id="checkbox-{{task.id}}" />
            <label for="checkbox-{{task.id}}">
                {{task.titleText}}
            </label>

            <a [routerLink]="['/details', task.id]"
               class="btn btn-default btn-xs">
                Show details &gt;
            </a>

            <button (click)="deleteTask(task)" class="btn btn-danger btn-xs">
                Delete
            </button>
        </h4>
        <p if.bind="task.detailsText" title="{{task.detailsText}}">
            {{task.detailsText}}
        </p>
        <div>
            <span title="Updated at {{task.updatedAt | date:'yyyy-MM-dd HH:mm:ss'}}" class="label label-info">
                Updated: {{task.updatedAt | dateRelative}}
            </span>&nbsp;
            <span class="label label-default">
                Created: {{task.createdAt | date:'yyyy-MM-dd'}}
            </span>
        </div>
    </div>
</div>

<div *ngIf="doneTaskItems.length" class="list-group">
    <h3>
        Done items
        <span *ngIf="doneTasksCount" class="badge">
            {{doneTasksCount}}
        </span>
    </h3>

    <div *ngFor="let task of doneTaskItems"
         class="list-group-item list-group-item-success {{task.isDone ? 'strike-through' : ''}}">
        <h4>
            <input [(ngModel)]="task.isDone" (change)="updateTask(task)"
                   type="checkbox" id="checkbox-{{task.id}}" />
            <label for="checkbox-{{task.id}}">
                {{task.titleText}}
            </label>

            <a [routerLink]="['/details', task.id]"
               class="btn btn-default btn-xs">
                Show details &gt;
            </a>

            <button (click)="deleteTask(task)" class="btn btn-danger btn-xs">
                Delete
            </button>
        </h4>
        <div>
            <span title="Updated at {{task.updatedAt | date:'yyyy-MM-dd HH:mm:ss'}}" class="label label-info">
                Updated: {{task.updatedAt | dateRelative}}
            </span>&nbsp;
            <span class="label label-default">
                Created: {{task.createdAt | date:'yyyy-MM-dd'}}
            </span>
        </div>
    </div>
</div>
